import './hero-burger-menu';
import './swiper-hero';
import './modal';
import './select';
import './swiper-programs';
import './swiper-theme-news';
import './swiper-content-news';
import './faq-accordion';
import './swiper-reviews';
